ALTER TABLE papers ADD COLUMN summary_md TEXT DEFAULT NULL;
ALTER TABLE papers ADD COLUMN tldr TEXT DEFAULT NULL;
ALTER TABLE papers ADD COLUMN model_used TEXT DEFAULT NULL;
ALTER TABLE papers ADD COLUMN summary_tokens INTEGER DEFAULT NULL;
ALTER TABLE papers ADD COLUMN last_summarized_at TEXT DEFAULT NULL;